apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-api
  labels:
    app: patient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: parasdongre/patient-api 
        ports:
        - containerPort: 8283
